language: php

services:
  - mysql

env:
  global:

branches:
  only:
  - master

php:
    - 7.0

before_install:

before_script:
  - ./app/config/setup/setup.sh

script:
  - ./vendor/phpunit/phpunit/phpunit --coverage-clover=tests/coverage/coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd
