language: php

services:
  - mysql

env:
  global:
    - ENABLE_CODE_COVERAGE="false"

php:
    - 7.0

before_install:
  - openssl aes-256-cbc -K $encrypted_af4a80b0e103_key -iv $encrypted_af4a80b0e103_iv -in ./.travis/deploy_key.pem -out ~\/.ssh/travis_rsa.pub -d

before_script:
  - ./app/config/setup/setup.sh
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then pip install --user codecov; fi;

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then phpunit --whitelist --coverage-clover=clover.xml; else phpunit; fi;

after_success:
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then echo clover.xml; fi;
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then codecov; fi;
    - eval "$(ssh-agent -s)" #start the ssh agent
    - chmod 600 .travis/deploy_key.pem # this key should have push access
    - ssh-add .travis/deploy_key.pem
    - git remote add deploy https://github.com/romainnorberg/construct-tim.git
    - git push deploy

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd
