language: php

services:
  - mysql

env:
  global:

branches:
  only:
  - master

php:
    - 7.0

before_install:

before_script:
  - ./app/config/setup/setup.sh

script:
  - ./vendor/phpunit/phpunit/phpunit ./tests

after_success:

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd
