language: php

services:
  - mysql

env:
  global:
    - ENABLE_CODE_COVERAGE="true"

php:
    - 7.0

before_script:
  - ./app/config/setup/setup.sh
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then composer require --dev satooshi/php-coveralls; fi

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then phpunit --whitelist --coverage-text --coverage-clover build/logs/clover.xml; else phpunit; fi;

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd

after_success:
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;
