language: php

services:
  - mysql

php:
    - 7.0

before_script:
  - ./app/config/setup/setup.sh

script:
  - phpunit

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd

after_success:
    - bash <(curl -s https://codecov.io/bash)
