language: php

php:
    - 7.0

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - npm install -g bower
  - bower install
  - npm install -g grunt-cli
  - npm install
  - php app/console assets:install --symlink && grunt symlink
  - grunt

script:
  - phpunit

notifications:
  email:
    -  romainnorberg@gmail.com
