language: php

services:
  - mysql

env:
  global:
    - ENABLE_CODE_COVERAGE="true"

php:
    - 7.0

before_script:
  - ./app/config/setup/setup.sh
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then pip install --user codecov; fi;

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then phpunit --whitelist --coverage-clover=clover.xml; else phpunit; fi;

after_success:
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then codecov; fi;

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd
