language: php

services:
  - mysql

env:
  global:
    - ENABLE_CODE_COVERAGE="true"

php:
    - 7.0

before_script:
  - ./app/config/setup/setup.sh

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then phpunit --whitelist --coverage-clover=coverage.xml; else phpunit; fi;

after_script:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email:
    -  romainnorberg@gmail.com
  slack: romain-norberg:AAraEIeAoipJXwSUDsDL5YOd

after_success:
    - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash); fi;
