easy_admin:
  site_name: 'CT Administration'
  design:
    color_scheme: 'light'
  list:
      actions:
          - { name: 'show', icon: 'search' }
          - { name: 'edit', icon: 'pencil' }

ivory_ck_editor:
  input_sync: true
  default_config: base_config
  configs:
    base_config:
      toolbar:
        - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link', 'Image'] }
