stfalcon_tinymce:
    selector: ".tinymce"
    language: "%locale%"
    tinymce_buttons:
        imageupload:
            title: "Upload image"
            image: "http://stfalcon.com/favicon.ico"
    use_callback_tinymce_init: true
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        admin:
             plugins:
                 - "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak spellchecker"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking"
                 - "table contextmenu directionality emoticons template textcolor paste fullpage textcolor colorpicker textpattern autoresize"
             toolbar1: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect"
             toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image imageupload media code | insertdatetime preview | forecolor backcolor"
             toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking template pagebreak restoredraft"
             menubar: false
             toolbar_items_size: 'small'
