vich_uploader:
    db_driver: orm
    mappings:
        ct_image:
            uri_prefix:         "/uploads/images"
            upload_destination: "%kernel.root_dir%/../web/uploads/images"
            namer:              vich_uploader.namer_uniqid

liip_imagine:
    driver:               imagick

    resolvers:

    loaders:

    filter_sets:
