knp_gaufrette:
    adapters:
        adapter_aws_s3_images:
            aws_s3:
                service_id: "shq.amazon.s3"
                bucket_name: "construct-tim-2016"
                options:
                    directory: 'images'
                    create: true
    filesystems:
        filesystem_aws_s3_images:
            adapter: adapter_aws_s3_images
    stream_wrapper: ~

vich_uploader:
    db_driver: orm
    storage:   gaufrette
    mappings:
        ct_image:
            uri_prefix:         "https://s3.eu-central-1.amazonaws.com/construct-tim-2016/images"
            upload_destination: filesystem_aws_s3_images
            namer:              vich_uploader.namer_uniqid

liip_imagine:
    driver:               imagick

    resolvers:
       cache_resolver_aws_s3:
          aws_s3:
              client_config:
                  credentials:
                      key: %s3_credentials_key%
                      secret: %s3_credentials_secret%
                  region: "eu-central-1"
                  version: "latest"
              bucket:     "construct-tim-2016"
              get_options:
                  Scheme: 'https'
              put_options:
                  CacheControl: 'max-age=86400'

    loaders:
        loader_aws_s3_images:
            stream:
                # This refers to knp_gaufrette filesystems configuration
                wrapper: gaufrette://filesystem_aws_s3_images/

    filter_sets:
        images_medium_thumb:
            data_loader: loader_aws_s3_images
            # We don't yet have a cache resolver configured
            cache: cache_resolver_aws_s3
            quality: 65
            filters:
                thumbnail: { size: [400, 400], mode: outbound }
        images_small_thumb:
            data_loader: loader_aws_s3_images
            # We don't yet have a cache resolver configured
            cache: cache_resolver_aws_s3
            quality: 65
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
