knp_gaufrette:
    adapters: ~
    filesystems: ~
    stream_wrapper: ~

vich_uploader:
    db_driver: orm
    storage:   gaufrette
    mappings:
        ct_image:
            upload_destination: "."
            namer:              vich_uploader.namer_uniqid

liip_imagine:
    driver:               imagick

    resolvers:

    loaders:

    filter_sets:
