imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin/ }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: construct_tim
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true

oneup_flysystem:
    adapters:
        ct_adapter:
            awss3v3:
                client: ct.s3_client
                bucket: "construct-tim-2016"
                prefix: ~
                options:
                  create: true

    filesystems:
        ct_image_fs_s3:
            adapter:    ct_adapter
            mount:      ct_image_fs_s3

vich_uploader:
    db_driver: orm
    storage:   flysystem
    mappings:
        ct_image:
            uri_prefix:         "http://construct-tim-2016.s3-website.eu-central-1.amazonaws.com"
            upload_destination: ct_image_fs_s3
            namer:              vich_uploader.namer_uniqid

liip_imagine:
    driver:               imagick

    resolvers:
       cache_resolver_aws_s3:
          aws_s3:
              client_config:
                  credentials:
                      key: %s3_credentials_key%
                      secret: %s3_credentials_secret%
                  region: "eu-central-1"
                  version: "latest"
              bucket:     "construct-tim-2016"
              get_options:
                  Scheme: 'https'
              put_options:
                  CacheControl: 'max-age=86400'

    loaders:
        loader_aws_s3_images:
            flysystem:
                filesystem_service: oneup_flysystem.ct_image_fs_s3_filesystem

    filter_sets:
        test_medium_thumb:
            data_loader: loader_aws_s3_images
            # We don't yet have a cache resolver configured
            cache: cache_resolver_aws_s3
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: outbound }
        test_small_thumb:
            data_loader: loader_aws_s3_images
            # We don't yet have a cache resolver configured
            cache: cache_resolver_aws_s3
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
