imports:
    - { resource: config.yml }
    - { resource: parameters_prod.php }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  error_log
            level: debug
        console:
            type:  console

staffim_rollbar:
    # Rollbar access token
    access_token: %rollbar_server_access_token%
    # PHP error level (see http://php.net/manual/en/function.error-reporting.php)
    error_level: -1
    # Values from scrub.parameters are replaced by the key for specified exceptions
    scrub:
        exceptions:
            - PDOException
        parameters:
            key: %rollbar_client_access_token%

ewz_recaptcha:
  public_key:  %ewz_recaptcha_public_key%
  private_key: %ewz_recaptcha_private_key%
  locale_key:  %kernel.default_locale%
