imports:
    - { resource: services/ }
    - { resource: "@AppBundle/Resources/config/services.yml" }

services:
    serializer.mapping.cache.apcu:
        class: Doctrine\Common\Cache\ApcuCache

    app.twig_extension:
        class:        AppBundle\Twig\RawDescriptionExtension
        public:       false
        tags:
            - { name: twig.extension }