services:
    admin.project_type:
        class: AppBundle\Admin\ProjectTypeAdmin
        arguments: [~, AppBundle\Entity\ProjectType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Type de projet }
        calls:
            - [ setTemplate, [edit, AppBundle::admin/edit.html.twig]]

    admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Projet }
        calls:
            - [ setTemplate, [edit, AppBundle::admin/edit.html.twig]]

    admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Page }
        calls:
            - [ setTemplate, [edit, AppBundle::admin/edit.html.twig]]

    admin.page_category:
        class: AppBundle\Admin\PageCategoryAdmin
        arguments: [~, AppBundle\Entity\PageCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Page catégorie }
        calls:
            - [ setTemplate, [edit, AppBundle::admin/edit.html.twig]]

    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }
        calls:
            - [ setTemplate, [edit, AppBundle::admin/edit.html.twig]]

    admin.tinymce:
        class: AppBundle\Admin\TinymceAdmin
        arguments: [~, ~, ~]
