imports:
    - { resource: s3.php }

parameters:

services:
    shq.amazon.s3Credentials:
      class: Aws\Credentials\Credentials
      arguments: ["%s3_credentials_key%", "%s3_credentials_secret%"]

    shq.amazon.s3:
      class: Aws\S3\S3Client
      arguments:
          -
              version: %s3_version%
              region: %s3_region%
              credentials: "@shq.amazon.s3Credentials"
