services:
    shq.amazon.s3Credentials:
      class: Aws\Credentials\Credentials
      arguments: ["%s3_credentials_key%", "%s3_credentials_secret%"]

    shq.amazon.s3:
      class: Aws\S3\S3Client
      arguments:
          -
              version: 'latest' # or 'latest'
              region: "eu-central-1" # 'eu-central-1' for example
              credentials: "@shq.amazon.s3Credentials"
